name: Github Pages Deploy

on:
  push:
    brances:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install
        run: npm install

      - name: Deploy
        run: npm run deploy